#pragma once

enum class InterruptCode : uint8_t
{
	DIV_BY_ZERO = 0,
	DEBUG,
	NON_MASKABLE_INT,
	BREAKPOINT,
	OVERFLOW,
	BOUND_RANGE,
	INV_OPCODE,
	DEVICE_UNAVAILABLE,
	DOUBLE_FAULT,
	INV_TSS = 10,
	NOT_PRESENT,
	STACK_SEGMANT_FAULT,
	GENRAL_PROTECTION_FAULT,
	PAGE_FAULT,
	KERNEL_FPU = 16,
	ALIGN_CHECK,
	MACHINE_CHECK,
	SIMF_FP,
	VIRTUALIZATION,
};

void register_all_interrupt_handlers();
